version: "3"
services:
  log_generator:
    image: catalinfetoiu/idp_project:log_generator
    networks:
      - app_network
  rabbitmq_service:
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 10s
      retries: 10
  rabbit_worker:
    image: catalinfetoiu/idp_project:log_generator
    networks:
      - app_network
  elasticsearch_service:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 10s
      retries: 10
  client:
    image: catalinfetoiu/idp_project:client
    networks:
      - app_network
networks:
  app_network:

